# Generated by Django 2.2.6 on 2021-01-01 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('profile_picture', models.ImageField(blank=True, default='Avatar/deafult-profile-image.png', upload_to='Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Pokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=9500, unique_for_date='publish')),
                ('poke_avatar', models.ImageField(blank=True, upload_to='Avatar_pokes')),
                ('poke_user', models.CharField(max_length=1000)),
                ('poke_date', models.CharField(max_length=9000)),
                ('poke_avatar1', models.ImageField(blank=True, upload_to='Avatar_pokes')),
                ('poke_user1', models.CharField(max_length=1000)),
                ('poke_date1', models.CharField(max_length=9000)),
                ('poke_avatar2', models.ImageField(blank=True, upload_to='Avatar_pokes')),
                ('poke_user2', models.CharField(max_length=1000)),
                ('poke_date2', models.CharField(max_length=9000)),
                ('poke_avatar3', models.ImageField(blank=True, upload_to='Avatar_pokes')),
                ('poke_user3', models.CharField(max_length=1000)),
                ('poke_date3', models.CharField(max_length=9000)),
                ('poke_add_image', models.ImageField(blank=True, upload_to='Avatar_pokes')),
                ('poke_add_me', models.CharField(max_length=1000)),
                ('poke_vectim_link', models.URLField(blank=True, max_length=128, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.author')),
            ],
        ),
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=9500, null=True, verbose_name='العنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=9500, unique_for_date='publish')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='صورة مناسبة')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Pokes')),
            ],
        ),
    ]
